### ISSUE TITLE
Create an input analysing scope

### ISSUE THREAD

**Issue by hdsdi3g** [mediaexmachina/mediadeepa#10]
- [x] ~~Allow/reject filters~~ was done on #1 
- [x] ~~Time limited / start from~~ was done on #1 
- [x] ~~Process duration limited~~ was done on #1 
- [ ] Can inject filters configuration => https://github.com/mediaexmachina/mediadeepa/issues/13
